"""Human-friendly names for source documents and exported files."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

_DISPLAY_TIMEZONE = ZoneInfo("Asia/Ho_Chi_Minh")
_REALTIME_PREFIX = "realtime_"
_FULL_TEXT_MODE = "full_text"


def _local_time(created_at: datetime) -> datetime:
    timestamp = created_at
    if timestamp.tzinfo is None:
        timestamp = timestamp.replace(tzinfo=timezone.utc)
    return timestamp.astimezone(_DISPLAY_TIMEZONE)


def is_realtime_filename(filename: str) -> bool:
    """Return whether a source name was generated by the realtime endpoint."""
    return Path(filename).name.startswith(_REALTIME_PREFIX)


def source_display_name(filename: str, created_at: datetime) -> str:
    """Return the source name shown in the library and document header."""
    if not is_realtime_filename(filename):
        return filename
    timestamp = _local_time(created_at)
    return f"Ghi âm trực tiếp · {timestamp:%d/%m/%Y %H:%M}"


def source_export_label(filename: str, created_at: datetime) -> str:
    """Return a concise source label suitable for a download filename."""
    if is_realtime_filename(filename):
        timestamp = _local_time(created_at)
        return f"Ghi âm {timestamp:%d-%m-%Y %H-%M}"
    return Path(filename).stem or "Tài liệu"


def source_document_label(filename: str, created_at: datetime) -> str:
    """Return the source metadata displayed inside an exported document."""
    if is_realtime_filename(filename):
        return source_display_name(filename, created_at)
    return Path(filename).stem or "Tài liệu"


def export_title(
    filename: str | None,
    created_at: datetime | None,
    document_mode: str,
) -> str:
    """Build a filename stem without leaking storage-oriented source names."""
    if filename is None or created_at is None:
        return "document"
    if document_mode == _FULL_TEXT_MODE:
        label = source_export_label(filename, created_at)
        return f"Toàn văn - {label}"
    return Path(filename).stem or "document"
